"""CDP cookie dumper.

Reads Chrome's `DevToolsActivePort` file, connects directly to the browser-level
WebSocket, and calls `Storage.getCookies` to dump every cookie in the default
context. Filters down to *.fudan.edu.cn related domains and writes:

- cookies/cookies.json   structured (incl. HttpOnly, expires, secure, etc.)
- cookies/cookies.txt    Netscape format (curl/wget/yt-dlp -b compatible)
- cookies/cookie-header.txt   one-line Cookie header for icourse.fudan.edu.cn

Use `refresh_cookies(target_host=...)` before each pipeline run since iCourse
cookies (PHPSESSID, _csrf, iPlanetDirectoryPro, etc.) expire on session timeouts.
"""
from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import websockets

from .config import Config, load_config

KEEP_DOMAIN_RE = re.compile(r"(fudan\.edu\.cn|fudan-icourse|icourse\.fudan)", re.IGNORECASE)


def _read_devtools_port(chrome_user_data_dir: str) -> tuple[int, str]:
    p = Path(chrome_user_data_dir) / "DevToolsActivePort"
    if not p.exists():
        raise FileNotFoundError(f"DevToolsActivePort not found at {p}; is Chrome running with --remote-debugging-port?")
    lines = p.read_text(encoding="utf-8").strip().split("\n")
    port = int(lines[0])
    ws_path = lines[1] if len(lines) > 1 else "/devtools/browser"
    return port, ws_path


async def _cdp_call(ws, method: str, params: dict | None = None, msg_id: int = 1) -> dict:
    payload = {"id": msg_id, "method": method, "params": params or {}}
    await ws.send(json.dumps(payload))
    while True:
        raw = await asyncio.wait_for(ws.recv(), timeout=15)
        m = json.loads(raw)
        if m.get("id") == msg_id:
            if "error" in m:
                raise RuntimeError(f"{method}: {m['error']}")
            return m.get("result", {})


async def _fetch_cookies(port: int, ws_path: str) -> list[dict]:
    url = f"ws://127.0.0.1:{port}{ws_path}"
    async with websockets.connect(url, max_size=64 * 1024 * 1024) as ws:
        result = await _cdp_call(ws, "Storage.getCookies", {})
        return result.get("cookies", [])


def _filter_fudan(cookies: Iterable[dict]) -> list[dict]:
    return [c for c in cookies if KEEP_DOMAIN_RE.search(c.get("domain", ""))]


def _to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by fudan-icourse-summarizer", ""]
    for c in cookies:
        domain = c["domain"]
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = c.get("expires", -1)
        expires = 0 if (not exp or exp < 0) else int(exp)
        lines.append("\t".join([domain, include_subdomains, path, secure, str(expires), c["name"], c["value"]]))
    return "\n".join(lines) + "\n"


def _cookie_header_for(cookies: list[dict], target_host: str) -> str:
    applies = []
    for c in cookies:
        dom = c["domain"]
        bare = dom.lstrip(".")
        if target_host == bare or target_host.endswith("." + bare):
            applies.append(c)
    return "; ".join(f"{c['name']}={c['value']}" for c in applies)


def refresh_cookies(cfg: Config | None = None, target_host: str = "icourse.fudan.edu.cn") -> dict:
    """Dump fresh cookies from the running Chrome to `cookies/` files.

    Returns a small summary dict with paths and cookie counts.
    """
    cfg = cfg or load_config()
    chrome_dir = cfg["chrome_user_data_dir"]
    port, ws_path = _read_devtools_port(chrome_dir)

    all_cookies = asyncio.run(_fetch_cookies(port, ws_path))
    fudan = _filter_fudan(all_cookies)

    cookies_dir = cfg.cookies_dir
    cookies_dir.mkdir(parents=True, exist_ok=True)

    by_domain: dict[str, list[dict]] = {}
    for c in fudan:
        by_domain.setdefault(c["domain"], []).append(c)

    (cookies_dir / "cookies.json").write_text(
        json.dumps(
            {
                "exported_at": datetime.now(timezone.utc).isoformat(),
                "total": len(fudan),
                "domains": sorted(by_domain.keys()),
                "by_domain": by_domain,
                "cookies": fudan,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    (cookies_dir / "cookies.txt").write_text(_to_netscape(fudan), encoding="utf-8")

    header = _cookie_header_for(fudan, target_host)
    (cookies_dir / "cookie-header.txt").write_text(header + "\n", encoding="utf-8")

    return {
        "total_browser_cookies": len(all_cookies),
        "fudan_cookies": len(fudan),
        "domains": sorted(by_domain.keys()),
        "header_len": len(header),
        "files": {
            "json": str(cookies_dir / "cookies.json"),
            "netscape": str(cookies_dir / "cookies.txt"),
            "header": str(cookies_dir / "cookie-header.txt"),
        },
    }


def load_cookie_header(cfg: Config | None = None) -> str:
    cfg = cfg or load_config()
    p = cfg.cookies_dir / "cookie-header.txt"
    if not p.exists():
        raise FileNotFoundError("No cookie-header.txt yet; run refresh_cookies() first.")
    return p.read_text(encoding="utf-8").strip()


if __name__ == "__main__":
    summary = refresh_cookies()
    print(json.dumps(summary, indent=2, ensure_ascii=False))
