"""Use the CDP Proxy (web-access skill) to open a livingroom page in a
background tab and read the freshly-signed `video.src`.

The signature has the form ?clientUUID=...&t=<userid>-<unix_ts>-<md5> and is
generated by `/static/cmcPlayer/cmcMediaPlayer.js` from a secret embedded in
the page. Reversing it is doable but fragile; letting Chrome compute it is
both simpler and version-tolerant.
"""
from __future__ import annotations

import json
import time
from typing import Any
from urllib.parse import urlencode

import requests

from .config import Config, load_config


def _session() -> requests.Session:
    """A bare session that ignores system proxy (Clash on 127.0.0.1:7890 etc.).

    The CDP proxy is always on localhost; respecting HTTP_PROXY would route
    these calls through Clash and silently break them.
    """
    s = requests.Session()
    s.trust_env = False
    return s


def _proxy(cfg: Config) -> str:
    return cfg["cdp_proxy_url"].rstrip("/")


def _new_tab(cfg: Config, url: str) -> str:
    """Open a background tab. Returns its targetId."""
    base = _proxy(cfg)
    # Block until the page reaches `load` event (or proxy timeout). For livingroom
    # this can take ~3-8 seconds.
    r = _session().get(f"{base}/new", params={"url": url}, timeout=120)
    r.raise_for_status()
    data = r.json()
    return data.get("targetId") or data.get("id") or data


def _navigate(cfg: Config, target_id: str, url: str) -> None:
    base = _proxy(cfg)
    r = _session().get(f"{base}/navigate", params={"target": target_id, "url": url}, timeout=120)
    r.raise_for_status()


def _eval(cfg: Config, target_id: str, js: str) -> Any:
    base = _proxy(cfg)
    r = _session().post(
        f"{base}/eval",
        params={"target": target_id},
        data=js.encode("utf-8"),
        timeout=60,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"/eval HTTP {r.status_code}: {r.text[:300]}")
    if not r.text.strip():
        raise RuntimeError(
            "/eval returned empty body — usually means the CDP proxy's sendCDP "
            "timed out (30s). Is Chrome reachable and is the JS expression fast enough?"
        )
    try:
        body = r.json()
    except ValueError as e:
        raise RuntimeError(f"/eval body is not JSON: {r.text[:300]!r}") from e
    if "error" in body:
        raise RuntimeError(f"eval error: {body['error']}")
    return body.get("value")


def _close(cfg: Config, target_id: str) -> None:
    base = _proxy(cfg)
    try:
        _session().get(f"{base}/close", params={"target": target_id}, timeout=10)
    except Exception:
        pass


def find_existing_livingroom_tab(cfg: Config, course_id: str, sub_id: str) -> str | None:
    base = _proxy(cfg)
    r = _session().get(f"{base}/targets", timeout=10)
    r.raise_for_status()
    targets = r.json()
    # Proxy may wrap in {value: [...]} or return plain list
    if isinstance(targets, dict):
        targets = targets.get("value", [])
    needle = f"course_id={course_id}"
    needle2 = f"sub_id={sub_id}"
    for t in targets:
        url = t.get("url", "")
        if "livingroom" in url and needle in url and needle2 in url:
            return t.get("targetId") or t.get("id")
    return None


# Read whatever the current page already has — no waiting, no mutation.
# Used when reusing an existing tab the user opened: if it has a signed src,
# we just steal it.
JS_READ_CURRENT_SRC = r"""
(function(){
  if (location.href.startsWith('chrome-error://') || location.href.startsWith('about:')) {
    return JSON.stringify({ src: null, error: 'page failed to load: ' + location.href });
  }
  var v = document.querySelector('video');
  if (!v) return JSON.stringify({ src: null, error: 'no <video> element', href: location.href });
  return JSON.stringify({
    src: v.src || v.currentSrc || null,
    currentSrc: v.currentSrc || null,
    readyState: v.readyState,
    duration: v.duration,
    href: location.href,
  });
})()
"""

# Wait for the iCourse SPA to render the player and set video.src. Polls up to
# 25 s (must stay below the proxy's 30 s sendCDP cap).
JS_WAIT_FOR_SIGNED_SRC = r"""
(async function(){
  if (location.href.startsWith('chrome-error://') || location.href.startsWith('about:')) {
    return JSON.stringify({ src: null, error: 'page failed to load: ' + location.href });
  }
  function readSrc() {
    var v = document.querySelector('video');
    if (!v) return null;
    return { src: v.src || v.currentSrc || null, currentSrc: v.currentSrc || null,
             readyState: v.readyState, duration: v.duration };
  }
  function hasSig(s) {
    return s && s.src && s.src.indexOf('clientUUID=') !== -1 && s.src.indexOf('t=') !== -1;
  }
  var deadline = Date.now() + 25000;
  while (Date.now() < deadline) {
    var s = readSrc();
    if (hasSig(s)) return JSON.stringify(s);
    await new Promise(r => setTimeout(r, 400));
  }
  return JSON.stringify(readSrc() || { src: null, error: 'video element never produced a signed URL within 25s' });
})()
"""


def _has_signed_src(info: Any) -> bool:
    if not info or not isinstance(info, dict):
        return False
    src = info.get("src") or info.get("currentSrc") or ""
    # Signed URL format observed in practice:
    #   ...mp4?clientUUID=<uuid>&t=<userid>-<unix_ts>-<md5_hex>
    return "clientUUID=" in src and "t=" in src


def fetch_signed_video_url(
    cfg: Config | None,
    course_id: str,
    sub_id: str,
    tenant_code: str = "222",
    reuse_existing_tab: bool = True,
    keep_tab_open: bool = True,
) -> dict[str, Any]:
    """Returns dict with `src` (signed video URL), `referer`, `targetId`.

    Strategy (in order of cheapness):
      1. Find a livingroom tab the user already opened. If it has a valid
         ?t= signature, use it directly — no navigation, no waiting.
      2. Otherwise, navigate that tab (or open a new background tab) to the
         URL and poke the video element to force preload, polling for a
         signed src.

    `keep_tab_open=True` by default so subsequent runs (or the user) can reuse
    the tab without paying the cold-start cost again.
    """
    cfg = cfg or load_config()
    query = urlencode({"course_id": course_id, "sub_id": sub_id, "tenant_code": tenant_code})
    url = f"https://icourse.fudan.edu.cn/livingroom?{query}"

    existing = None
    if reuse_existing_tab:
        existing = find_existing_livingroom_tab(cfg, course_id, sub_id)

    # Step 1: try to steal an already-good signature from the existing tab.
    if existing:
        try:
            raw = _eval(cfg, existing, JS_READ_CURRENT_SRC)
            info = json.loads(raw) if isinstance(raw, str) else (raw or {})
            if _has_signed_src(info):
                print(f"[signed_url] reusing live signature from existing tab {existing[:8]}", flush=True)
                return {
                    "src": info["src"],
                    "referer": url,
                    "duration": info.get("duration"),
                    "ready_state": info.get("readyState"),
                    "target_id": existing,
                    "opened_new": False,
                    "reused_signature": True,
                }
        except Exception as e:
            print(f"[signed_url] existing tab unusable ({e}); will navigate fresh", flush=True)

    # Step 2: navigate (existing) or open (new) — then force preload.
    target_id = existing
    opened_new = False
    if target_id is None:
        print("[signed_url] opening new background tab", flush=True)
        target_id = _new_tab(cfg, url)
        opened_new = True
    else:
        print(f"[signed_url] re-navigating existing tab {target_id[:8]}", flush=True)
        _navigate(cfg, target_id, url)

    try:
        raw = _eval(cfg, target_id, JS_WAIT_FOR_SIGNED_SRC)
        info = json.loads(raw) if isinstance(raw, str) else (raw or {})
        if not _has_signed_src(info):
            hint = info.get("error") if isinstance(info, dict) else None
            raise RuntimeError(
                "video element never produced a signed src"
                + (f" — {hint}" if hint else "")
                + ". Check (1) Clash is OFF so icourse is reachable, "
                "(2) the recording has a playback already (sub_status=6), "
                "(3) you're logged in (cookies fresh), "
                "(4) if the issue persists, manually open the livingroom URL "
                "in Chrome and wait until the video plays — then rerun pipeline "
                "with --skip-cookies (the script will reuse your tab's signature)."
            )
        return {
            "src": info["src"],
            "referer": url,
            "duration": info.get("duration"),
            "ready_state": info.get("readyState"),
            "target_id": target_id,
            "opened_new": opened_new,
            "reused_signature": False,
        }
    finally:
        # Default to KEEPING the tab open so the next run is cheap.
        if opened_new and not keep_tab_open:
            _close(cfg, target_id)


if __name__ == "__main__":
    import sys

    course_id = sys.argv[1] if len(sys.argv) > 1 else "34945"
    sub_id = sys.argv[2] if len(sys.argv) > 2 else "563930"
    res = fetch_signed_video_url(None, course_id, sub_id)
    print(json.dumps(res, indent=2, ensure_ascii=False))
